model_list: []

router_settings:
  routing_strategy: simple-shuffle
  num_retries: 2
  timeout: 60

general_settings:
  master_key: sk-local-master
  database_url: postgres://xhub:xhub_dev_password@postgres:5432/xhub?sslmode=disable
  redis_url: redis://redis:6379/1
  store_model_in_db: true
